const REVENUECAT_API_KEY_IOS = process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_IOS;
const REVENUECAT_API_KEY_ANDROID = process.env.EXPO_PUBLIC_REVENUECAT_API_KEY_ANDROID;

if (!REVENUECAT_API_KEY_IOS || !REVENUECAT_API_KEY_ANDROID) {
    throw new Error("Missing REVENUECAT_API_KEY_IOS or REVENUECAT_API_KEY_ANDROID in environment variables");
}

export const REVENUECAT_API_KEYS = {
    ios: REVENUECAT_API_KEY_IOS,
    android: REVENUECAT_API_KEY_ANDROID,
};

